[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmds = [". /opt/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"]
